using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Equals
{
    class MyClass
    {
        private int someNumber;
        private string someString;

        // constructor
        public MyClass(int num, string str)
        {
            this.someNumber = num;
            this.someString = str;
        }

        public override bool Equals(object obj)
        {
            // return base.Equals(obj);   this was generated by IntelliSense (by default)
            
            // is this object of my type? and not null?
            if(obj is MyClass && obj != null)
            {
                // comparison
                // create a temp variable
                MyClass temp;
                // casting: object passed in was type obj so you needed to cast it
                // explicitly to be a MyClass object in order to compare
                temp = (MyClass)obj;

                // to compare simple numbers can use == operator
                // when comparing strings, however, then you must use
                // the Equals() method. 
                if ((temp.someNumber == this.someNumber) &&
                   temp.someString.Equals(this.someString)) return true;
                else return false;
            }
            return false;
        }

    }
}
